name: 10 - workflow environment

on:
 workflow_dispatch:
  inputs:
   target-env:
    type: environment
    default: staging
jobs:
 echo:
  runs-on: ubuntu-latest
  steps:
   - name: echo vars
     run: |
      echo "Input is: ${{env.TARGET_VAR}}"
