name: 05- 1- Event Filters and activity Types

on:
 pull_request:
   types:
      - opened
      - syncronised
   branches:
     - master

jobs:
 echo:
   runs-on: ubuntu-latest
   steps:
     - run: echo "running whenerver a PR is required or syncronised and base branch is matser"
     
 
