name: 15 - workflow - matrices

on:
 workflow_dispatch:


jobs:
 backward_compatability:
  name: ${{matrix.os}}-${{matrix.node}}
  runs-on: ${{matrix.os}}
  strategy:
   matrix: 
    node-version: [v22.6.0,v21.7.3]
    os:
     - ubuntu-latest
     - windows-latest
     - macos-latest
    include:
     - os: ubuntu-latest
       node-version: v16
    exclude:
      - os: macos-latest
        node-version: v22.6.0,v21.7.3
  steps:
    - uses: actions/setup-node@v4
      with:
       node-version: ${{ matrix.node-version}}
    - name: Perform test
      run: echo "running test os and node version ${{matrix.os}} and ${{matrix.node-version}}"
     

   
