name: 15 - workflow - matrices

on:
 workflow_dispatch:


jobs:
 backward_compatability:
  name: ${{matrix.os}} - ${{matrix.node}}
  runs-on: ${{matrix.os}}
  strategy:
   matrix: 
    node-version: [24,23,22]
    os:
     - ubuntu-latest
     - windows-latest
  steps:
    - uses: actions/setup-node@v4
      with:
       ${{ matrix.node-version}}
    - name: Perform test
      run: echo "running test os and node version ${{matrix.os}} and ${{matrix.node-version}}"
     

   
